language: python
python:
# TODO: should python 2.6 be supported?
#- 2.6
- 2.7
# TODO: should python 3.4 be supported?
#- 3.4
install:
- pip install nose
- pip install numpy
- pip install --install-option='--no-cython-compile' cython
- git clone https://github.com/esc/bcolz.git
- export PYTHONPATH=$(pwd)/bcolz:${PYTHONPATH}
- python setup.py build_ext --inplace
script:
- nosetests bquery
notifications:
email: false
